"""added normalized titles to project and tasks to add unique indices off of

Revision ID: e213cf6e812e
Revises: aac18327e9ac
Create Date: 2026-07-02 18:38:36.951575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e213cf6e812e'
down_revision: Union[str, Sequence[str], None] = 'aac18327e9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('normalized_title', sa.String(), nullable=True))
    op.execute("UPDATE projects SET normalized_title = LOWER(TRIM(title))")
    op.create_unique_constraint(None, 'projects', ['normalized_title', 'created_by'])
    op.add_column('tasks', sa.Column('normalized_title', sa.String(), nullable=True))
    op.execute("UPDATE tasks SET normalized_title = LOWER(TRIM(title))")
    op.create_unique_constraint(None, 'tasks', ['normalized_title', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'normalized_title')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'normalized_title')
    # ### end Alembic commands ###
